const ApiRoutes = {
    LOGIN:{
        path:'/users/login',
        authenticate:false
    },
    SIGNUP:{
        path:'/users/createUser',
        authenticate:false
    },
    GET_ALL_APPROVED_EVENTS:{
        path:'/events/getAllApprovedEvents',
        authenticate:true
    },
    GET_ALL_APPROVED_EVENTS_BY_CATEGORY:{
        path:'/events/getAllApprovedEventsByCategory',
        authenticate:true
    },
    GET_ALL_EVENTS:{
        path:'/events/getAllEvents',
        authenticate:true
    },
    GET_BLOGS_BY_USER_ID:{
        path:'/blogs/getBlogsByUserId',
        authenticate:true
    },
    CREATE_EVENT:{
        path:'/events/createEvent',
        authenticate:true
    },
    GET_EVENT_BY_ID:{
        path:'/events/getEventById',
        authenticate:true
    },
    BOOK_EVENT:{
        path:'/events/buyEvent',
        authenticate:true
    },
    CREATE_ORDER:{
        path:'/razorpay/create-order',
        authenticate:false
    },
    UPDATE_STATUS:{
        path:'/events/updateStatus',
        authenticate:true
    },
    UPDATE_ORDER:{
        path:'/events/updateOrder',
        authenticate:true
    },
    UPDATE_LIKES:{
        path:'/blogs/updateLikes',
        authenticate:true
    },
    GET_ALL_USERS:{
        path:'/users/getAllUsers',
        authenticate:true
    },
    GET_RESET_LINK:{
        path:'/users/forgetPassword',
        authenticate:false
    },
    PASSWORD_RESET:{
        path:'/users/resetpassword',
        authenticate:false
    },
    ACTIVATE_USER:{
        path:'/users/activateUser',
        authenticate:false
    },
    GET_EVENTS_BY_USERID:{
        path:'/events/getEventsByUserId',
        authenticate:true
    },
    GET_EVENTS_BY_ADMIN:{
        path:'/events/getEventsByAdmin',
        authenticate:true
    },
    SEND_TICKET_EMAIL:{
        path:'/events/sendOrderEmail',
        authenticate:true
    }

}

export default ApiRoutes